version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 730335460548.dkr.ecr.us-east-1.amazonaws.com/ets-frontend)
  pre_build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t ets-frontend .
      - docker tag ets-frontend:latest 730335460548.dkr.ecr.us-east-1.amazonaws.com/ets-frontend:latest
  build:
    commands:
      - echo Build completed on `date`
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 730335460548.dkr.ecr.us-east-1.amazonaws.com/ets-frontend:latest
artifacts:
  files:
    - '**/*'
